main: main.c
	$(CC) main.c -o main -Wall -Wextra -pedantic -std=c99

# This filr allows you to simply run my main
# $(cc) exapands
# -wall - All Warnings
# -Wextra and -pendantic , more warnings
# -std=c99 , helps declare variables